LiftScoring/Models/ErrorViewModel.cs
namespace LiftScoring.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LiftScoring/Models/LiftSession.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LiftScoring.Models;
public class LiftSession
{
    [Key]
    public int Id { get; set; }
    public DateTime LiftDate { get; set; }

    [ForeignKey(nameof(LifterModel.Id))]
    public int LifterId { get; set; }

    public int Score { get; set; }

}

LiftScoring/Models/LiftSets.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LiftScoring.Models
{
    public class LiftSets
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey(nameof(LiftType.Id))]
        public int Type_Id { get; set; }

        public int Weight { get; set; }

        public int Reps { get; set; }
    }
}

LiftScoring/Models/LiftType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LiftScoring.Models;
public class LiftType
{
    [Key]
    public int Id { get; set; }

    [ForeignKey(nameof(LiftSession.Id))]
    public int SessionId { get; set; }
    public string Name { get; set; }
    public int HighScore { get; set; }
}

LiftScoring/Models/LifterModel.cs
using System.ComponentModel.DataAnnotations;

namespace LiftScoring.Models;
public class LifterModel
{
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public bool isFemale { get; set; }
    public double DeadLift { get; set; }
    public double SquatLift { get; set; }
    public double BenchLift { get; set; }
    public double OverheadPressLift { get; set; }
    public double CurlLift { get; set; }
    public double RowLift { get; set; }

}

LiftScoring/Controllers/HomeController.cs
using LiftScoring.Models;
using Microsoft.AspNetCore.Mvc;
using MySqlConnector;
using System.Diagnostics;

namespace LiftScoring.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        var lifter = new LifterModel
        {
            Name = "Lixa",
            isFemale = true,
            DeadLift = 125,
            SquatLift = 75,
            BenchLift = 50,
            CurlLift = 50,
            OverheadPressLift = 50,
            RowLift = 65
        };
        return View(lifter);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

LiftScoring/Controllers/ScoringController.cs
using Microsoft.AspNetCore.Mvc;

namespace LiftScoring.Controllers
{
    public class ScoringController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<double> GetScoreByGenderAsync(double liftWeight, bool isFemale)
        {
            var score = isFemale ? (liftWeight * 1.8) : liftWeight;
            return score;
        }
    }
}
}

LiftScoring/Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace LiftScoring.Controllers
{
    public class WorkoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LiftScoring/Views/Home/Index.cshtml
@model LifterModel

@{
    ViewData["Title"] = "Home Page";
}

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>*@
<!-- Row 1 -->
  <div class="container-fluid bg-light p-5">
    <div class="row">
      <div class="col-12 text-center">
        <h1>Lift Scoring</h1>
        <p>Compete with yourself, friends, or colleagues.</p>
      </div>
    </div>
  </div>

  <!-- Row 2 -->
  <div class="container my-5 text-center">
    <div class="row">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Deadlift</h5>
            <p class="card-text">@Model.DeadLift</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Squat</h5>
            <p class="card-text">@Model.SquatLift</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Bench</h5>
            <p class="card-text">@Model.BenchLift</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Row 3 -->
  <div class="container my-5 text-center">
    <div class="row">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">OverheadPress</h5>
            <p class="card-text">@Model.OverheadPressLift</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Curl</h5>
            <p class="card-text">@Model.CurlLift</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Row</h5>
            <p class="card-text">@Model.RowLift</p>
          </div>
        </div>
      </div>
    </div>
  </div>

LiftScoring/Views/Scoring/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

  <div class="container-fluid bg-light p-5">
    <div class="row">
      <div class="col-12 text-center">
        <h1>Lift Scoring</h1>
        <p>Enter the total weight of the lift</p>
      </div>
    </div>
  </div>

<!-- Row 1 -->
  <div class="container my-5">
    <div class="row">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">DeadLift</h5>
            <input type="number" class="form-control" id="deadLiftInput" placeholder="Enter a number">
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Squat</h5>
            <input type="number" class="form-control" id="squatLiftInput" placeholder="Enter a number">
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Bench</h5>
            <input type="number" class="form-control" placeholder="Enter a number">
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Row 2 -->
  <div class="container my-5">
    <div class="row">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Overhead Press</h5>
            <input type="number" class="form-control" placeholder="Enter a number">
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Row</h5>
            <input type="number" class="form-control" placeholder="Enter a number">
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Curl</h5>
            <input type="number" class="form-control" placeholder="Enter a number">
          </div>
        </div>
      </div>
    </div>
  </div>

LiftScoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LiftScoring</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LiftScoring.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LiftScoring</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scoring" asp-action="Index">Scoring</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="Index">Add Workout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LiftScoring - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LiftScoring/Views/Workout/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container-fluid bg-light p-5">
    <div class="row">
        <div class="col-12 text-center">
            <h1>Save your Workout</h1>
            <p>Enter the information about your lifts.</p>
        </div>
    </div>
</div>

<div class="container my-5">

    <div class="row">
        <div class="col-md-12 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">DeadLift</h5>
                    <select name="liftType">
                        <option>Deadlift</option>
                        <option>Squat</option>
                        <option>Bench Press</option>
                        <option>Overhead Press</option>
                        <option>Power Clean</option>
                        <option>Clean and Jerk</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Weight</h5>
                    <input type="text" class="form-control" name="weight_1" placeholder="Enter the weight used for this set.">
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Reps</h5>
                    <input type="text" class="form-control" placeholder="Enter number of reps in this set.">
                </div>
            </div>
        </div>
    </div>

</div>